//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ServicesManagement.Web.wsOrdenesPorEmpacar2 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Soriana_WMSSoap", Namespace="http://tempuri.org/")]
    public partial class Soriana_WMS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GeneraEmbarqueOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Soriana_WMS() {
            this.Url = global::ServicesManagement.Web.Properties.Settings.Default.ServicesManagement_Web_wsOrdenesPorEmpacar2_Soriana_WMS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GeneraEmbarqueCompletedEventHandler GeneraEmbarqueCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GeneraEmbarque", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GeneraEmbarque([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] EmbarqueRequest embarqueRequest) {
            object[] results = this.Invoke("GeneraEmbarque", new object[] {
                        embarqueRequest});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GeneraEmbarqueAsync(EmbarqueRequest embarqueRequest) {
            this.GeneraEmbarqueAsync(embarqueRequest, null);
        }
        
        /// <remarks/>
        public void GeneraEmbarqueAsync(EmbarqueRequest embarqueRequest, object userState) {
            if ((this.GeneraEmbarqueOperationCompleted == null)) {
                this.GeneraEmbarqueOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGeneraEmbarqueOperationCompleted);
            }
            this.InvokeAsync("GeneraEmbarque", new object[] {
                        embarqueRequest}, this.GeneraEmbarqueOperationCompleted, userState);
        }
        
        private void OnGeneraEmbarqueOperationCompleted(object arg) {
            if ((this.GeneraEmbarqueCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GeneraEmbarqueCompleted(this, new GeneraEmbarqueCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EmbarqueRequest {
        
        private Embarques embarquesField;
        
        private string siglasClienteField;
        
        /// <remarks/>
        public Embarques Embarques {
            get {
                return this.embarquesField;
            }
            set {
                this.embarquesField = value;
            }
        }
        
        /// <remarks/>
        public string siglasCliente {
            get {
                return this.siglasClienteField;
            }
            set {
                this.siglasClienteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Embarques {
        
        private Embarque embarqueField;
        
        /// <remarks/>
        public Embarque Embarque {
            get {
                return this.embarqueField;
            }
            set {
                this.embarqueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Embarque {
        
        private int cantidadField;
        
        private string citaField;
        
        private int codigoPostalField;
        
        private string coloniaField;
        
        private string contactoField;
        
        private string direccionField;
        
        private string fechaLimiteField;
        
        private int montoAseguradoField;
        
        private string poblacionField;
        
        private string razonSocialField;
        
        private string referencia2Field;
        
        private string referencia3Field;
        
        private string referencia4Field;
        
        private string referencia5Field;
        
        private string referencia6Field;
        
        private string referencia7Field;
        
        private string servicioField;
        
        private double telefonoField;
        
        private string[] uccListField;
        
        /// <remarks/>
        public int cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
            }
        }
        
        /// <remarks/>
        public string cita {
            get {
                return this.citaField;
            }
            set {
                this.citaField = value;
            }
        }
        
        /// <remarks/>
        public int codigoPostal {
            get {
                return this.codigoPostalField;
            }
            set {
                this.codigoPostalField = value;
            }
        }
        
        /// <remarks/>
        public string colonia {
            get {
                return this.coloniaField;
            }
            set {
                this.coloniaField = value;
            }
        }
        
        /// <remarks/>
        public string contacto {
            get {
                return this.contactoField;
            }
            set {
                this.contactoField = value;
            }
        }
        
        /// <remarks/>
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
            }
        }
        
        /// <remarks/>
        public string fechaLimite {
            get {
                return this.fechaLimiteField;
            }
            set {
                this.fechaLimiteField = value;
            }
        }
        
        /// <remarks/>
        public int montoAsegurado {
            get {
                return this.montoAseguradoField;
            }
            set {
                this.montoAseguradoField = value;
            }
        }
        
        /// <remarks/>
        public string poblacion {
            get {
                return this.poblacionField;
            }
            set {
                this.poblacionField = value;
            }
        }
        
        /// <remarks/>
        public string razonSocial {
            get {
                return this.razonSocialField;
            }
            set {
                this.razonSocialField = value;
            }
        }
        
        /// <remarks/>
        public string referencia2 {
            get {
                return this.referencia2Field;
            }
            set {
                this.referencia2Field = value;
            }
        }
        
        /// <remarks/>
        public string referencia3 {
            get {
                return this.referencia3Field;
            }
            set {
                this.referencia3Field = value;
            }
        }
        
        /// <remarks/>
        public string referencia4 {
            get {
                return this.referencia4Field;
            }
            set {
                this.referencia4Field = value;
            }
        }
        
        /// <remarks/>
        public string referencia5 {
            get {
                return this.referencia5Field;
            }
            set {
                this.referencia5Field = value;
            }
        }
        
        /// <remarks/>
        public string referencia6 {
            get {
                return this.referencia6Field;
            }
            set {
                this.referencia6Field = value;
            }
        }
        
        /// <remarks/>
        public string referencia7 {
            get {
                return this.referencia7Field;
            }
            set {
                this.referencia7Field = value;
            }
        }
        
        /// <remarks/>
        public string servicio {
            get {
                return this.servicioField;
            }
            set {
                this.servicioField = value;
            }
        }
        
        /// <remarks/>
        public double telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ucc", IsNullable=false)]
        public string[] uccList {
            get {
                return this.uccListField;
            }
            set {
                this.uccListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GeneraEmbarqueCompletedEventHandler(object sender, GeneraEmbarqueCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GeneraEmbarqueCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GeneraEmbarqueCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591